# Generated by Django 3.2.15 on 2024-05-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'локация', 'verbose_name_plural': 'локации'},
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время запроса'),
        ),
    ]
