# Generated by Django 3.2.15 on 2024-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_rename_phone_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена продукта на момент заказа'),
            preserve_default=False,
        ),
    ]
