# Generated by Django 3.2.15 on 2024-05-16 12:53

from django.db import migrations, models


def set_product_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')

    for order_item in OrderItem.objects.all().iterator():

        product_price = Product.objects.filter(
            id=order_item.product_id).values_list('price', flat=True).first()
        order_item.product_price = product_price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена продукта на момент заказа'),
            preserve_default=False,
        ),
        migrations.RunPython(set_product_price),
    ]
