# Generated by Django 3.2.15 on 2024-05-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('НО', 'Необработан'), ('ПР', 'Передан ресторану'), ('Пк', 'Передан курьеру'), ('В', 'Выполнен')], db_index=True, default='НО', max_length=2, verbose_name='статус'),
        ),
    ]
