# Generated by Django 3.2.15 on 2024-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default=None, max_length=200, verbose_name='комментарий', null=True),
            preserve_default=False,
        ),
    ]
