# Generated by Django 3.2.15 on 2024-05-18 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='позвонили в'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='доставили в'),
        ),
        migrations.AddField(
            model_name='order',
            name='registrated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='зарегистрирован в'),
        ),
    ]
