# Generated by Django 3.2.15 on 2024-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20240518_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Н', 'Наличные'), ('Э', 'Электронно')], db_index=True, default='Н', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
