# Generated by Django 3.2.15 on 2024-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('НО', 'Необработан'), ('ПР', 'Передан ресторану'), ('Г', 'Готовится'), ('Пк', 'Передан курьеру'), ('В', 'Выполнен')], db_index=True, default='НО', max_length=2, verbose_name='статус'),
        ),
    ]
