# Generated by Django 3.2.15 on 2024-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20240519_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registrated',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
    ]
