# Generated by Django 3.2.15 on 2024-06-13 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20240603_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registrated',
            new_name='registered',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
